[2024-11-12T02:52:57.054+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T02:52:57.073+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: modeling_pipeline.Random_Forest_model_Train manual__2024-11-12T02:52:52.526778+00:00 [queued]>
[2024-11-12T02:52:57.080+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: modeling_pipeline.Random_Forest_model_Train manual__2024-11-12T02:52:52.526778+00:00 [queued]>
[2024-11-12T02:52:57.080+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-12T02:52:57.099+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Random_Forest_model_Train> on 2024-11-12 02:52:52.526778+00:00
[2024-11-12T02:52:57.124+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=81) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-12T02:52:57.127+0000] {standard_task_runner.py:63} INFO - Started process 106 to run task
[2024-11-12T02:52:57.125+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'modeling_pipeline', 'Random_Forest_model_Train', 'manual__2024-11-12T02:52:52.526778+00:00', '--job-id', '992', '--raw', '--subdir', 'DAGS_FOLDER/dag_script_model.py', '--cfg-path', '/tmp/tmpb_5m9q1j']
[2024-11-12T02:52:57.131+0000] {standard_task_runner.py:91} INFO - Job 992: Subtask Random_Forest_model_Train
[2024-11-12T02:52:57.246+0000] {task_command.py:426} INFO - Running <TaskInstance: modeling_pipeline.Random_Forest_model_Train manual__2024-11-12T02:52:52.526778+00:00 [running]> on host 5039cd089413
[2024-11-12T02:52:57.336+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MLOPS' AIRFLOW_CTX_DAG_ID='modeling_pipeline' AIRFLOW_CTX_TASK_ID='Random_Forest_model_Train' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T02:52:52.526778+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T02:52:52.526778+00:00'
[2024-11-12T02:52:57.338+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T02:52:57.525+0000] {logging_mixin.py:188} WARNING - 2024/11/12 02:52:57 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
