[2024-11-03T02:37:47.781+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-03T02:37:47.790+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: datapipeline_new.check_anomalies_missing_vals_train manual__2024-11-03T02:36:44.429080+00:00 [queued]>
[2024-11-03T02:37:47.794+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: datapipeline_new.check_anomalies_missing_vals_train manual__2024-11-03T02:36:44.429080+00:00 [queued]>
[2024-11-03T02:37:47.794+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-03T02:37:47.864+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): check_anomalies_missing_vals_train> on 2024-11-03 02:36:44.429080+00:00
[2024-11-03T02:37:47.868+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=241) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-03T02:37:47.869+0000] {standard_task_runner.py:63} INFO - Started process 250 to run task
[2024-11-03T02:37:47.869+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'datapipeline_new', 'check_anomalies_missing_vals_train', 'manual__2024-11-03T02:36:44.429080+00:00', '--job-id', '720', '--raw', '--subdir', 'DAGS_FOLDER/dag_script.py', '--cfg-path', '/tmp/tmp_b97akjd']
[2024-11-03T02:37:47.870+0000] {standard_task_runner.py:91} INFO - Job 720: Subtask check_anomalies_missing_vals_train
[2024-11-03T02:37:47.887+0000] {task_command.py:426} INFO - Running <TaskInstance: datapipeline_new.check_anomalies_missing_vals_train manual__2024-11-03T02:36:44.429080+00:00 [running]> on host 7ffb0854de89
[2024-11-03T02:37:47.932+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MLOPS' AIRFLOW_CTX_DAG_ID='datapipeline_new' AIRFLOW_CTX_TASK_ID='check_anomalies_missing_vals_train' AIRFLOW_CTX_EXECUTION_DATE='2024-11-03T02:36:44.429080+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-03T02:36:44.429080+00:00'
[2024-11-03T02:37:47.935+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-03T02:37:47.959+0000] {baseoperator.py:400} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-11-03T02:37:47.966+0000] {dag_script.py:101} INFO - Anomalies detected: ['Total missing values: 2793']
[2024-11-03T02:37:47.967+0000] {dag_script.py:103} INFO - send_anomaly_alert_remove_cols_train
[2024-11-03T02:37:47.967+0000] {python.py:237} INFO - Done. Returned value was: send_anomaly_alert_remove_cols_train
[2024-11-03T02:37:47.968+0000] {branch.py:36} INFO - Branch into send_anomaly_alert_remove_cols_train
[2024-11-03T02:37:47.968+0000] {skipmixin.py:178} INFO - Following branch send_anomaly_alert_remove_cols_train
[2024-11-03T02:37:47.978+0000] {skipmixin.py:246} INFO - Skipping tasks []
[2024-11-03T02:37:47.985+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-03T02:37:47.993+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=datapipeline_new, task_id=check_anomalies_missing_vals_train, run_id=manual__2024-11-03T02:36:44.429080+00:00, execution_date=20241103T023644, start_date=20241103T023747, end_date=20241103T023747
[2024-11-03T02:37:48.009+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-03T02:37:48.044+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-03T02:37:48.045+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
