[2024-11-05T01:23:57.389+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-05T01:23:57.488+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: datapipeline_new.anamolies_vals_test manual__2024-11-05T01:22:21.867548+00:00 [queued]>
[2024-11-05T01:23:57.493+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: datapipeline_new.anamolies_vals_test manual__2024-11-05T01:22:21.867548+00:00 [queued]>
[2024-11-05T01:23:57.493+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-05T01:23:57.500+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): anamolies_vals_test> on 2024-11-05 01:22:21.867548+00:00
[2024-11-05T01:23:57.511+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=452) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-05T01:23:57.512+0000] {standard_task_runner.py:63} INFO - Started process 461 to run task
[2024-11-05T01:23:57.512+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'datapipeline_new', 'anamolies_vals_test', 'manual__2024-11-05T01:22:21.867548+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/dag_script.py', '--cfg-path', '/tmp/tmp58c5std6']
[2024-11-05T01:23:57.514+0000] {standard_task_runner.py:91} INFO - Job 170: Subtask anamolies_vals_test
[2024-11-05T01:23:57.544+0000] {task_command.py:426} INFO - Running <TaskInstance: datapipeline_new.anamolies_vals_test manual__2024-11-05T01:22:21.867548+00:00 [running]> on host b260d3fe343d
[2024-11-05T01:23:57.587+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MLOPS' AIRFLOW_CTX_DAG_ID='datapipeline_new' AIRFLOW_CTX_TASK_ID='anamolies_vals_test' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T01:22:21.867548+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T01:22:21.867548+00:00'
[2024-11-05T01:23:57.588+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-05T01:23:57.597+0000] {anamoly_detection.py:21} INFO - Data loaded from /opt/***/dags/DataPreprocessing/src/data_store_pkl_files/test_data/no_null_test_data.pkl.
[2024-11-05T01:23:57.602+0000] {anamoly_detection.py:48} INFO - Outliers in 'pm25' replaced with median value 5.8.
[2024-11-05T01:23:57.604+0000] {anamoly_detection.py:65} INFO - Negative values in 'pm25' replaced with 0.
[2024-11-05T01:23:57.605+0000] {anamoly_detection.py:70} INFO - Cleaned DataFrame saved as '/opt/***/dags/DataPreprocessing/src/data_store_pkl_files/test_data/no_anamoly_test_data.pkl'.
[2024-11-05T01:23:57.605+0000] {anamoly_detection.py:87} INFO - Total anomalies: ["380 outliers detected in 'pm25' column."]
[2024-11-05T01:23:57.605+0000] {anamoly_detection.py:88} INFO - Total outliers replaced: 380
[2024-11-05T01:23:57.605+0000] {anamoly_detection.py:89} INFO - Total negative values replaced: 0
[2024-11-05T01:23:57.605+0000] {python.py:237} INFO - Done. Returned value was: ["380 outliers detected in 'pm25' column."]
[2024-11-05T01:23:57.605+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-05T01:23:57.614+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=datapipeline_new, task_id=anamolies_vals_test, run_id=manual__2024-11-05T01:22:21.867548+00:00, execution_date=20241105T012221, start_date=20241105T012357, end_date=20241105T012357
[2024-11-05T01:23:57.656+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-05T01:23:57.668+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-05T01:23:57.668+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
