[2024-11-12T07:01:07.174+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T07:01:07.184+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: modeling_pipeline.Best_Model manual__2024-11-12T06:58:45.272245+00:00 [queued]>
[2024-11-12T07:01:07.187+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: modeling_pipeline.Best_Model manual__2024-11-12T06:58:45.272245+00:00 [queued]>
[2024-11-12T07:01:07.187+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-11-12T07:01:07.193+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Best_Model> on 2024-11-12 06:58:45.272245+00:00
[2024-11-12T07:01:07.201+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=331) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-12T07:01:07.202+0000] {standard_task_runner.py:63} INFO - Started process 340 to run task
[2024-11-12T07:01:07.203+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'modeling_pipeline', 'Best_Model', 'manual__2024-11-12T06:58:45.272245+00:00', '--job-id', '1110', '--raw', '--subdir', 'DAGS_FOLDER/dag_script_model.py', '--cfg-path', '/tmp/tmpvx4pukx_']
[2024-11-12T07:01:07.207+0000] {standard_task_runner.py:91} INFO - Job 1110: Subtask Best_Model
[2024-11-12T07:01:07.234+0000] {task_command.py:426} INFO - Running <TaskInstance: modeling_pipeline.Best_Model manual__2024-11-12T06:58:45.272245+00:00 [running]> on host 5039cd089413
[2024-11-12T07:01:07.269+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MLOPS' AIRFLOW_CTX_DAG_ID='modeling_pipeline' AIRFLOW_CTX_TASK_ID='Best_Model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T06:58:45.272245+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T06:58:45.272245+00:00'
[2024-11-12T07:01:07.270+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T07:01:07.378+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T07:01:07.379+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/bestmodel.py", line 386, in main
    model, best_rmse, best_experiment_name, best_run_id = get_best_model_and_load_weights(experiment_names)
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/bestmodel.py", line 374, in get_best_model_and_load_weights
    best_model = load_prophet_model(directory_weights_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/bestmodel.py", line 303, in load_prophet_model
    prophetmodel = ProphetPM25Model(train_file=None, test_file=None, lambda_value=None, model_save_path=filepath)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ModelDevelopment/Validation/Prophet.py", line 33, in __init__
    self.model = pickle.load(f)
                 ^^^^^^^^^^^^^^
_pickle.UnpicklingError: invalid load key, '{'.
[2024-11-12T07:01:07.385+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=modeling_pipeline, task_id=Best_Model, run_id=manual__2024-11-12T06:58:45.272245+00:00, execution_date=20241112T065845, start_date=20241112T070107, end_date=20241112T070107
[2024-11-12T07:01:07.391+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1110 for task Best_Model (invalid load key, '{'.; 340)
[2024-11-12T07:01:07.433+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-12T07:01:07.447+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T07:01:07.447+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
