[2024-11-05T01:23:43.124+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-05T01:23:43.216+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: datapipeline_new.data_remove_cols_test manual__2024-11-05T01:22:21.867548+00:00 [queued]>
[2024-11-05T01:23:43.221+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: datapipeline_new.data_remove_cols_test manual__2024-11-05T01:22:21.867548+00:00 [queued]>
[2024-11-05T01:23:43.221+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-05T01:23:43.226+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_remove_cols_test> on 2024-11-05 01:22:21.867548+00:00
[2024-11-05T01:23:43.236+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=392) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-05T01:23:43.237+0000] {standard_task_runner.py:63} INFO - Started process 401 to run task
[2024-11-05T01:23:43.237+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'datapipeline_new', 'data_remove_cols_test', 'manual__2024-11-05T01:22:21.867548+00:00', '--job-id', '164', '--raw', '--subdir', 'DAGS_FOLDER/dag_script.py', '--cfg-path', '/tmp/tmpw2mfiv3p']
[2024-11-05T01:23:43.238+0000] {standard_task_runner.py:91} INFO - Job 164: Subtask data_remove_cols_test
[2024-11-05T01:23:43.273+0000] {task_command.py:426} INFO - Running <TaskInstance: datapipeline_new.data_remove_cols_test manual__2024-11-05T01:22:21.867548+00:00 [running]> on host b260d3fe343d
[2024-11-05T01:23:43.336+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MLOPS' AIRFLOW_CTX_DAG_ID='datapipeline_new' AIRFLOW_CTX_TASK_ID='data_remove_cols_test' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T01:22:21.867548+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T01:22:21.867548+00:00'
[2024-11-05T01:23:43.337+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-05T01:23:43.351+0000] {removal_of_uneccesary_cols.py:20} INFO - Data loaded from /opt/***/dags/DataPreprocessing/src/data_store_pkl_files/test_data/pivoted_test_data.pkl.
[2024-11-05T01:23:43.352+0000] {removal_of_uneccesary_cols.py:35} WARNING - None of the specified columns ['co', 'no', 'no2', 'o3', 'so2'] exist in the DataFrame.
[2024-11-05T01:23:43.354+0000] {removal_of_uneccesary_cols.py:62} INFO - Set 'date' column as index successfully.
[2024-11-05T01:23:43.354+0000] {removal_of_uneccesary_cols.py:97} ERROR - Anomalies detected; skipping saving the cleaned data.
[2024-11-05T01:23:43.354+0000] {python.py:237} INFO - Done. Returned value was: ["None of the columns ['co', 'no', 'no2', 'o3', 'so2'] exist in the DataFrame"]
[2024-11-05T01:23:43.355+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-05T01:23:43.367+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=datapipeline_new, task_id=data_remove_cols_test, run_id=manual__2024-11-05T01:22:21.867548+00:00, execution_date=20241105T012221, start_date=20241105T012343, end_date=20241105T012343
[2024-11-05T01:23:43.380+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-05T01:23:43.396+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-05T01:23:43.396+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
